# SEO settings
title: "Piyush's Blog"
title2: "" # default: ""
description: "Piyush Tiwary's Blog"
keywords: "Piyush, Blog, Competitive, Programming, Machine, Learning, Development, Internship, Codeforces, Hackerrank"
url: http://aquarius31.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: https://github.com/aquarius31/aquarius31.github.io
disqus_shortname: "aquarius31"
twitter_username: "aquarius31"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Piyush Tiwary"
  job      : "Sophomore at IIT Patna"
  bio      : ""
  thumb    : /images/author.jpg
  email    : piyushtiwary31@gmail.com
  url      : http://aquarius31.github.io
  github   : http://github.com/aquarius31
  twitter  : https://twitter.com/piyusht_31
  facebook : https://www.facebook.com/phenomenal1.31
  linkedin : http://linkedin.com/in/aquarius31

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@piyushtiwary31"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

# plugins
plugins:
  - jekyll-seo-tag
exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
